name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v2
        name: Build the Docker image
        run: docker buildx build --no-cache --platform linux/arm64,linux/amd64 . --file Dockerfile --tag charts-ci:$(date +%s)
